import type { Post, User, Review } from './types';
export const demoUser: User = {
  id: 'demo-you',
  name: 'Alex Rivera',
  handle: 'alexmakes',
  avatar: 'AR',
  bio: 'Indie maker designing calmer tools for creative work.',
  credibility: 86,
  credits: 12,
};
const mina: User = {
  id: 'u1',
  name: 'Mina Park',
  handle: 'minabuilds',
  avatar: 'MP',
  bio: 'Product designer shipping tiny useful things.',
  credibility: 94,
  credits: 38,
};
const theo: User = {
  id: 'u2',
  name: 'Theo Santos',
  handle: 'theocodes',
  avatar: 'TS',
  bio: 'Making the internet feel human.',
  credibility: 89,
  credits: 24,
};
const sam: User = {
  id: 'u3',
  name: 'Sam Okafor',
  handle: 'samships',
  avatar: 'SO',
  bio: 'Developer and weekend gardener.',
  credibility: 91,
  credits: 45,
};
export const posts: Post[] = [
  {
    id: 'quiet-tab',
    creator: mina,
    title: 'Quiet Tab',
    pitch: 'A gentle new-tab space that helps you choose one meaningful thing.',
    url: 'https://example.com/quiet-tab',
    image:
      'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1600&q=85',
    stage: 'Beta',
    version: 'v0.8',
    chips: ['First impression', 'Clarity', 'Would you use it?'],
    context:
      'I kept opening tabs without knowing why. Quiet Tab replaces the noise with one intention, a small focus timer, and nothing else. I’m testing whether the value is obvious in five seconds.',
    customQuestions: ['Does the empty space feel calm or unfinished?'],
    vibes: 184,
    createdAt: '2026-08-27T10:00:00Z',
    reviewCount: 23,
    commentCount: 8,
    trending: 98,
    versions: [
      'v0.8 · Refined onboarding',
      'v0.7 · Added focus timer',
      'v0.5 · First public build',
    ],
  },
  {
    id: 'field-notes',
    creator: theo,
    title: 'Field Notes',
    pitch: 'Turn a neighborhood walk into a beautifully mapped visual journal.',
    url: 'https://example.com/field-notes',
    image:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',
    stage: 'Prototype',
    version: 'v0.3',
    chips: ['Navigation', 'Trust', 'Mobile flow'],
    context:
      'A weekend prototype for people who notice small details. Save a photo, thought, and location without turning the walk into content creation.',
    customQuestions: ['Would you share a journal publicly?'],
    vibes: 129,
    createdAt: '2026-08-26T14:00:00Z',
    reviewCount: 11,
    commentCount: 5,
    trending: 78,
    versions: ['v0.3 · Map clusters', 'v0.2 · Private journals'],
  },
  {
    id: 'pantry-pal',
    creator: sam,
    title: 'Pantry Pal',
    pitch: 'Dinner ideas from what you already have—without an account or a lecture.',
    url: 'https://example.com/pantry-pal',
    image:
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=85',
    stage: 'Live',
    version: 'v1.2',
    chips: ['Onboarding', 'Usability', 'Recipe quality'],
    context:
      'Food waste is a UX problem. Add a few ingredients and get flexible, unfussy meal directions. This version focuses on faster ingredient entry.',
    customQuestions: [],
    vibes: 247,
    createdAt: '2026-08-24T09:00:00Z',
    reviewCount: 38,
    commentCount: 14,
    trending: 91,
    versions: ['v1.2 · Faster pantry entry', 'v1.1 · Dietary filters', 'v1.0 · Launch'],
  },
  {
    id: 'kindred',
    creator: mina,
    title: 'Kindred',
    pitch: 'A private ritual for keeping long-distance friendships close.',
    url: 'https://example.com/kindred',
    image:
      'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1600&q=85',
    stage: 'Idea',
    version: 'v0.1',
    chips: ['Concept', 'Emotional tone'],
    context:
      'Exploring lightweight prompts that make reaching out feel natural, never like relationship admin.',
    customQuestions: ['Which prompt would make you come back?'],
    vibes: 76,
    createdAt: '2026-08-28T08:00:00Z',
    reviewCount: 4,
    commentCount: 2,
    trending: 70,
    versions: ['v0.1 · Concept test'],
  },
];
export const seedReview: Review = {
  id: 'r1',
  postId: 'quiet-tab',
  author: theo,
  impression: 'Peaceful and immediately focused.',
  clarity: 5,
  trust: 4,
  usability: 4,
  tryIt: 'Yes',
  reason: 'It solves a habit I recognize without asking for too much.',
  improvement: 'Make the keyboard shortcut visible on the first visit.',
  implemented: false,
  createdAt: '2026-08-27T12:00:00Z',
};
